import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>AutoAIQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>Auto Answer Intelligence Querying</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              Team Sidiki
            </a>
          </div>
        </div>

        <div>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className="container">
            <div className="card">
                <form className='form' action="#" method="POST">
                    <label for="requete">Émettre une requête :</label>
                    <textarea id="requete" name="requete" rows="5" required></textarea>
                    <button type="submit" className='button'>Soumettre</button>

                    <label for="reponse">Envoyer la réponse de la requête émise :</label>
                    <textarea id="reponse" name="reponse" rows="15" required></textarea> 
                </form>
            </div>
         </div>
        </div>
      </main>
    </>
  )
}
